
CREATE TABLE Users (
    UserId INT IDENTITY PRIMARY KEY NOT NULL,
    FullName NVARCHAR(100),
    Email NVARCHAR(100) NOT NULL,
    UserPassword NVARCHAR(100) NOT NULL
);

CREATE TABLE Admins (
    AdminId INT IDENTITY PRIMARY KEY NOT NULL,
    FullName NVARCHAR(100),
    Username NVARCHAR(100) NOT NULL,
    AdminPassword NVARCHAR(100) NOT NULL
);

CREATE TABLE News (
    NewsId INT IDENTITY PRIMARY KEY NOT NULL,
    Header NVARCHAR(200) NULL,
    Content NVARCHAR(MAX) NULL,
    Posted DATETIME DEFAULT GETDATE(),
    AdminId INT FOREIGN KEY REFERENCES Admins(AdminId)
);

CREATE TABLE UserSave (
    SaveId INT IDENTITY PRIMARY KEY NOT NULL,
    UserId INT FOREIGN KEY REFERENCES Users(UserId),
    NewsId INT FOREIGN KEY REFERENCES News(NewsId),
    Saved DATETIME DEFAULT GETDATE()
);
