//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public Admin()
        {
            this.News = new HashSet<News>();
        }
    
        public int AdminId { get; set; }
        public string FullName { get; set; }
        public string Username { get; set; }
        public string AdminPassword { get; set; }
    
        public virtual ICollection<News> News { get; set; }
    }
}
