//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public News()
        {
            this.UserSaves = new HashSet<UserSave>();
        }
    
        public int NewsId { get; set; }
        public string Header { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> Posted { get; set; }
        public Nullable<int> AdminId { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual ICollection<UserSave> UserSaves { get; set; }
    }
}
