//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSave
    {
        public int SaveId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> NewsId { get; set; }
        public Nullable<System.DateTime> Saved { get; set; }
    
        public virtual News News { get; set; }
        public virtual User User { get; set; }
    }
}
